export enum BackgroundMessageType {
    INIT,
    RESPONSE,
    PROGRESS,
    READ_MNF_ARCHIVE,
    LOAD_FILE_CONTENT,
    EXTRACT_FILES,
    GET_FILE_METADATA,
    GET_BASENAME,
    GET_DIRNAME,
    RESOLVE_PATH,
    SEARCH_FILES
}
