// SPDX-FileCopyrightText: 2025 sirinsidiator
//
// SPDX-License-Identifier: GPL-3.0-or-later

import 'svelte/elements';
import type { JSX as IonicJSX } from '@stencil/core';

interface CommonAttributes {
    onkeydown?: (event: KeyboardEvent) => void;
}

type KebabCase<T extends string> = T extends `${infer Head}${infer Tail}`
    ? Tail extends Uncapitalize<Tail>
        ? `${Head}${KebabCase<Tail>}`
        : `${Head}-${KebabCase<Lowercase<Tail>>}`
    : T;

type KebabCaseKeys<T> = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    [K in keyof T as K extends `on${infer _}` ? K : KebabCase<K & string>]: T[K];
};

type SvelteStyleEventHooks<T> = {
    [K in keyof T as K extends `on${infer Rest}` ? `on${Uncapitalize<Rest>}` : K]: T[K];
};

type CorrectedAttributes<T> = SvelteStyleEventHooks<KebabCaseKeys<T>>;

declare module 'svelte/elements' {
    export interface SvelteHTMLElements extends IonicJSX.IntrinsicElements {
        /** THIS PORTION OF THE FILE IS AUTOGENERATED BY scripts/ionicComponentTypesToSvelte.js. DO NOT EDIT. */
        'ion-accordion': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-accordion`]>;
        'ion-accordion-group': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-accordion-group`]>;
        'ion-action-sheet': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-action-sheet`]>;
        'ion-alert': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-alert`]>;
        'ion-app': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-app`]>;
        'ion-avatar': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-avatar`]>;
        'ion-back-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-back-button`]>;
        'ion-backdrop': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-backdrop`]>;
        'ion-badge': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-badge`]>;
        'ion-breadcrumb': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-breadcrumb`]>;
        'ion-breadcrumbs': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-breadcrumbs`]>;
        'ion-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-button`]>;
        'ion-buttons': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-buttons`]>;
        'ion-card': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-card`]>;
        'ion-card-content': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-card-content`]>;
        'ion-card-header': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-card-header`]>;
        'ion-card-subtitle': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-card-subtitle`]>;
        'ion-card-title': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-card-title`]>;
        'ion-checkbox': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-checkbox`]>;
        'ion-chip': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-chip`]>;
        'ion-col': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-col`]>;
        'ion-content': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-content`]>;
        'ion-datetime': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-datetime`]>;
        'ion-datetime-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-datetime-button`]>;
        'ion-fab': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-fab`]>;
        'ion-fab-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-fab-button`]>;
        'ion-fab-list': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-fab-list`]>;
        'ion-footer': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-footer`]>;
        'ion-grid': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-grid`]>;
        'ion-header': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-header`]>;
        'ion-img': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-img`]>;
        'ion-infinite-scroll': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-infinite-scroll`]>;
        'ion-infinite-scroll-content': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-infinite-scroll-content`]>;
        'ion-input': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-input`]>;
        'ion-input-otp': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-input-otp`]>;
        'ion-input-password-toggle': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-input-password-toggle`]>;
        'ion-item': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-item`]>;
        'ion-item-divider': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-item-divider`]>;
        'ion-item-group': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-item-group`]>;
        'ion-item-option': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-item-option`]>;
        'ion-item-options': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-item-options`]>;
        'ion-item-sliding': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-item-sliding`]>;
        'ion-label': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-label`]>;
        'ion-list': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-list`]>;
        'ion-list-header': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-list-header`]>;
        'ion-loading': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-loading`]>;
        'ion-menu': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-menu`]>;
        'ion-menu-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-menu-button`]>;
        'ion-menu-toggle': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-menu-toggle`]>;
        'ion-modal': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-modal`]>;
        'ion-nav': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-nav`]>;
        'ion-nav-link': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-nav-link`]>;
        'ion-note': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-note`]>;
        'ion-picker': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-picker`]>;
        'ion-picker-column': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-picker-column`]>;
        'ion-picker-column-option': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-picker-column-option`]>;
        'ion-picker-legacy': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-picker-legacy`]>;
        'ion-picker-legacy-column': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-picker-legacy-column`]>;
        'ion-popover': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-popover`]>;
        'ion-progress-bar': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-progress-bar`]>;
        'ion-radio': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-radio`]>;
        'ion-radio-group': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-radio-group`]>;
        'ion-range': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-range`]>;
        'ion-refresher': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-refresher`]>;
        'ion-refresher-content': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-refresher-content`]>;
        'ion-reorder': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-reorder`]>;
        'ion-reorder-group': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-reorder-group`]>;
        'ion-ripple-effect': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-ripple-effect`]>;
        'ion-route': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-route`]>;
        'ion-route-redirect': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-route-redirect`]>;
        'ion-router': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-router`]>;
        'ion-router-link': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-router-link`]>;
        'ion-router-outlet': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-router-outlet`]>;
        'ion-row': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-row`]>;
        'ion-searchbar': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-searchbar`]>;
        'ion-segment': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-segment`]>;
        'ion-segment-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-segment-button`]>;
        'ion-segment-content': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-segment-content`]>;
        'ion-segment-view': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-segment-view`]>;
        'ion-select': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-select`]>;
        'ion-select-modal': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-select-modal`]>;
        'ion-select-option': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-select-option`]>;
        'ion-select-popover': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-select-popover`]>;
        'ion-skeleton-text': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-skeleton-text`]>;
        'ion-spinner': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-spinner`]>;
        'ion-split-pane': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-split-pane`]>;
        'ion-tab': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-tab`]>;
        'ion-tab-bar': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-tab-bar`]>;
        'ion-tab-button': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-tab-button`]>;
        'ion-tabs': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-tabs`]>;
        'ion-text': CommonAttributes & CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-text`]>;
        'ion-textarea': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-textarea`]>;
        'ion-thumbnail': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-thumbnail`]>;
        'ion-title': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-title`]>;
        'ion-toast': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-toast`]>;
        'ion-toggle': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-toggle`]>;
        'ion-toolbar': CommonAttributes &
            CorrectedAttributes<IonicJSX.IntrinsicElements[`ion-toolbar`]>;
        /** END AUTOGENERATED CONTENT. */
    }
}

export {}; // ensure this is not an ambient module
